# Generated by Django 5.2.17 on 2026-09-07 16:05

import apps.core.validators
import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.events_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('organizer', models.CharField(blank=True, help_text="e.g. 'Youth Ministry', 'Church Office'", max_length=150)),
                ('registration_info', models.TextField(blank=True, help_text="Instructions if registration is required, e.g. 'RSVP at the church office by Friday.'")),
                ('external_link', models.URLField(blank=True, help_text='Optional link — registration form, more info, livestream, etc.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
