# Generated by Django 5.2.17 on 2026-09-07 14:23

import apps.core.validators
import apps.homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(choices=[('cross', 'Cross'), ('book', 'Book'), ('users', 'People / Fellowship'), ('heart', 'Heart / Service')], default='cross', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Creed Item',
                'verbose_name_plural': 'Creed Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, default='Welcome to 35 Onwe Road Church of Christ', max_length=100)),
                ('hero_headline', models.CharField(default='A Place to Worship, Grow and Serve', help_text="Main headline. Use the 'accent' field below for the single word/phrase you want highlighted in gold.", max_length=200)),
                ('hero_headline_accent', models.CharField(blank=True, help_text="A word/phrase from the headline above to render in gold, e.g. 'Grow'.", max_length=50)),
                ('hero_description', models.TextField(blank=True, default="We are a community of believers passionate about worship, growing in God's Word, and reaching out with His love.")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=apps.homepage.models.homepage_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('hero_cta_primary_text', models.CharField(default='Plan Your Visit', max_length=50)),
                ('hero_cta_primary_url', models.CharField(blank=True, default='#visit', max_length=255)),
                ('hero_cta_secondary_text', models.CharField(blank=True, default='Watch Sermons', max_length=50)),
                ('hero_cta_secondary_url', models.CharField(blank=True, default='#', max_length=255)),
                ('about_eyebrow', models.CharField(blank=True, default='About Us', max_length=100)),
                ('about_heading', models.CharField(blank=True, default='Faith. Family. Impact.', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to=apps.homepage.models.homepage_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('about_cta_text', models.CharField(blank=True, default='Our Beliefs', max_length=50)),
                ('about_cta_url', models.CharField(blank=True, default='#', max_length=255)),
                ('visit_cta_heading', models.CharField(blank=True, default='Join Us This Sunday', max_length=200)),
                ('visit_cta_description', models.TextField(blank=True)),
                ('visit_cta_image', models.ImageField(blank=True, null=True, upload_to=apps.homepage.models.homepage_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('visit_cta_button_text', models.CharField(blank=True, default='Find Us', max_length=50)),
                ('visit_cta_button_url', models.CharField(blank=True, default='#', max_length=255)),
                ('show_creed_section', models.BooleanField(default=True)),
                ('show_about_section', models.BooleanField(default=True)),
                ('show_service_times_section', models.BooleanField(default=True)),
                ('show_events_section', models.BooleanField(default=False)),
                ('show_sermons_section', models.BooleanField(default=False)),
                ('show_ministries_section', models.BooleanField(default=False)),
                ('show_news_section', models.BooleanField(default=False)),
                ('show_gallery_section', models.BooleanField(default=False)),
                ('show_school_section', models.BooleanField(default=False)),
                ('show_visit_cta_section', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
    ]
