# Generated by Django 5.2.17 on 2026-09-07 14:53

import apps.core.validators
import apps.ministries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(help_text="e.g. 'Senior Minister', 'Elder'", max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.ministries.models.ministries_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('bio', models.TextField(blank=True)),
                ('public_email', models.EmailField(blank=True, help_text='Only shown publicly if filled in.', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive leaders are hidden from the public site.')),
                ('user', models.OneToOneField(blank=True, help_text='Link to a CMS login only if this leader is also a Minister who signs in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.ministries.models.ministries_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('meeting_info', models.CharField(blank=True, help_text="e.g. 'Saturdays, 4:00 PM, Fellowship Hall'", max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries_created', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries_led', to='ministries.leader')),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
