# Generated by Django 5.2.17 on 2026-09-09 03:44

import apps.core.validators
import apps.school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, default='Church School', max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=apps.school.models.school_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('about_preview', models.TextField(blank=True, help_text='Short paragraph about the school shown on this page.')),
                ('programs_preview', models.TextField(blank=True, help_text='Short overview of programs/classes offered.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'School Info',
                'verbose_name_plural': 'School Info',
            },
        ),
    ]
