# Generated by Django 5.2.17 on 2026-09-07 12:33

import apps.church_settings.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='35 Onwe Road Church of Christ', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Short phrase shown near the church name, e.g. in the footer.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.church_settings.models.church_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.church_settings.models.church_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text="Paste a Google Maps 'Embed a map' src URL only.")),
                ('footer_short_description', models.TextField(blank=True)),
                ('default_seo_title', models.CharField(blank=True, max_length=255)),
                ('default_seo_description', models.CharField(blank=True, max_length=300)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to=apps.church_settings.models.church_upload_path, validators=[apps.core.validators.validate_image_file])),
            ],
            options={
                'verbose_name': 'Church Settings',
                'verbose_name_plural': 'Church Settings',
            },
        ),
    ]
