# Generated by Django 5.2.17 on 2026-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_settings', '0002_servicetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Contact form submissions are emailed here. Leave blank to use the server's default configuration.", max_length=254),
        ),
    ]
