# Generated by Django 5.2.17 on 2026-09-13 14:06

import apps.core.validators
import apps.gallery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(upload_to=apps.gallery.models.gallery_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('category', models.CharField(choices=[('worship', 'Worship'), ('community', 'Community'), ('events', 'Events'), ('ministries', 'Ministries'), ('outreach', 'Outreach'), ('special_moments', 'Special Moments'), ('church_life', 'Church Life'), ('bible_studies', 'Bible Studies')], max_length=20)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the image for screen readers. If left blank, the title is used instead.', max_length=255)),
                ('photo_date', models.DateField(help_text='Date shown on the photo card.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured photos are prioritized in homepage previews.')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Optional — link this photo to the event it was taken at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='events.event')),
            ],
            options={
                'ordering': ['order', '-photo_date'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
