# Generated by Django 5.2.17 on 2026-09-08 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Support the Church', max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text="Explain how giving supports the church's work — shown above the account details.")),
            ],
            options={
                'verbose_name': 'Support Page Content',
                'verbose_name_plural': 'Support Page Content',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'General Offering', 'Building Fund'", max_length=100)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('additional_info', models.CharField(blank=True, help_text='e.g. mobile money details, or a note.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('support_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='pages.supportpagecontent')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
