# Generated by Django 5.2.17 on 2026-09-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_supportpagecontent_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='active_members_count',
            field=models.CharField(blank=True, help_text="Shown in the 'Church at a Glance' stats row, e.g. '500+'.", max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Short intro paragraph shown under the hero heading.'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_heading',
            field=models.CharField(blank=True, default='A Church for Today, A Family for Life.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='years_of_impact',
            field=models.CharField(blank=True, help_text="Shown in the 'Church at a Glance' stats row, e.g. '5+'.", max_length=20),
        ),
    ]
