# Generated by Django 5.2.17 on 2026-09-07 15:30

import apps.core.validators
import apps.sermons.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('date_delivered', models.DateField()),
                ('scripture_reference', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.sermons.models.sermons_upload_path, validators=[apps.core.validators.validate_image_file])),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=apps.sermons.models.sermons_upload_path, validators=[apps.core.validators.validate_audio_file])),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link. We embed external video rather than hosting it ourselves.')),
                ('notes_pdf', models.FileField(blank=True, help_text='Sermon notes as a downloadable PDF.', null=True, upload_to=apps.sermons.models.sermons_upload_path, validators=[apps.core.validators.validate_pdf_file])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons_created', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='ministries.leader')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermoncategory')),
            ],
            options={
                'ordering': ['-date_delivered'],
            },
        ),
    ]
